# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = true
toolbarMode = "viewer"

# WebRTC specific settings
[webrtc]
rtcConfiguration = true
asyncProcessing = true
